const now = new Date().toISOString();
const oneHourAgo = new Date(Date.now() - 3600000).toISOString();
const tomorrowStart = new Date(Date.now() + 86400000);
tomorrowStart.setHours(7, 0, 0, 0);
const tomorrowEnd = new Date(tomorrowStart.getTime() + 28800000); // +8h

export const SEED_PERSONNEL = [
  {
    personnel_id: 'pers-001',
    name: 'Lars Erik Andersen',
    role: 'Patrulje',
    unit: 'Enhet Alpha',
    status: 'available',
    phone: '+47 920 11 001',
    email: 'l.andersen@beredskap.no',
    certifications: 'Skytevåpen, Førstehjelp',
    created_at: now,
    updated_at: now,
  },
  {
    personnel_id: 'pers-002',
    name: 'Ingrid Solberg',
    role: 'Medisinsk',
    unit: 'Enhet Bravo',
    status: 'available',
    phone: '+47 920 11 002',
    email: 'i.solberg@beredskap.no',
    certifications: 'Paramedic, ACLS, Kirurgi',
    created_at: now,
    updated_at: now,
  },
  {
    personnel_id: 'pers-003',
    name: 'Bjørn Haugen',
    role: 'Delta',
    unit: 'Enhet Delta',
    status: 'on-duty',
    phone: '+47 920 11 003',
    email: 'b.haugen@beredskap.no',
    certifications: 'Sprengning, Klatring, Skytevåpen',
    created_at: now,
    updated_at: now,
  },
  {
    personnel_id: 'pers-004',
    name: 'Kari Nilsen',
    role: 'Etterretning',
    unit: 'Enhet Charlie',
    status: 'available',
    phone: '+47 920 11 004',
    email: 'k.nilsen@beredskap.no',
    certifications: 'Analyse, OSINT',
    created_at: now,
    updated_at: now,
  },
  {
    personnel_id: 'pers-005',
    name: 'Tor Magne Bakke',
    role: 'Kommando',
    unit: 'KO-stab',
    status: 'available',
    phone: '+47 920 11 005',
    email: 't.bakke@beredskap.no',
    certifications: 'Lederskap, Taktikk, Samband',
    created_at: now,
    updated_at: now,
  },
  {
    personnel_id: 'pers-006',
    name: 'Silje Aaberg',
    role: 'Logistikk',
    unit: 'Støtteavdeling',
    status: 'off',
    phone: '+47 920 11 006',
    email: 's.aaberg@beredskap.no',
    certifications: 'Kjøretøy klasse C, Forsyning',
    created_at: now,
    updated_at: now,
  },
  {
    personnel_id: 'pers-007',
    name: 'Magnus Lund',
    role: 'Patrulje',
    unit: 'Enhet Alpha',
    status: 'sick',
    phone: '+47 920 11 007',
    email: 'm.lund@beredskap.no',
    certifications: 'Skytevåpen, Kjøring',
    created_at: now,
    updated_at: now,
  },
  {
    personnel_id: 'pers-008',
    name: 'Hanne Kristiansen',
    role: 'Støtte',
    unit: 'Enhet Bravo',
    status: 'available',
    phone: '+47 920 11 008',
    email: 'h.kristiansen@beredskap.no',
    certifications: 'Sanitet, Kommunikasjon',
    created_at: now,
    updated_at: now,
  },
];

export const SEED_EQUIPMENT = [
  {
    equipment_id: 'eq-001',
    name: 'Politibil P-17',
    type: 'vehicle',
    status: 'available',
    assigned_to: 'pers-001',
    last_known_lat: 59.9139,
    last_known_lng: 10.7522,
    notes: 'BMW 5-serie, utrustet med blålys og bur',
  },
  {
    equipment_id: 'eq-002',
    name: 'Transportbil T-03',
    type: 'vehicle',
    status: 'available',
    assigned_to: 'pers-006',
    last_known_lat: 59.9275,
    last_known_lng: 10.7486,
    notes: 'Mercedes Sprinter, stor lastekapasitet',
  },
  {
    equipment_id: 'eq-003',
    name: 'Drone DJI-M300',
    type: 'drone',
    status: 'available',
    assigned_to: 'pers-004',
    last_known_lat: 59.9182,
    last_known_lng: 10.7563,
    notes: 'Termisk kamera, 50 min flygetid',
  },
  {
    equipment_id: 'eq-004',
    name: 'Sambandssettet RS-08',
    type: 'radio',
    status: 'deployed',
    assigned_to: 'pers-003',
    last_known_lat: 59.9100,
    last_known_lng: 10.7600,
    notes: 'Nødnett-kompatibel, kryptert',
  },
  {
    equipment_id: 'eq-005',
    name: 'Medisinsk utstyrspakke M-1',
    type: 'medical',
    status: 'available',
    assigned_to: 'pers-002',
    last_known_lat: 59.9201,
    last_known_lng: 10.7450,
    notes: 'TCCC utstyr, tourniquet, IV-pakke',
  },
];

export const SEED_SHIFTS = [
  {
    shift_id: 'shift-001',
    personnel_id: 'pers-003',
    operation_name: 'Operasjon Nordvakt',
    shift_start: oneHourAgo,
    shift_end: new Date(Date.now() + 7 * 3600000).toISOString(),
    notes: 'Nattskift, Delta-innsats',
  },
  {
    shift_id: 'shift-002',
    personnel_id: 'pers-001',
    operation_name: 'Rutinepatrulje Oslo Sentrum',
    shift_start: tomorrowStart.toISOString(),
    shift_end: tomorrowEnd.toISOString(),
    notes: 'Dagskift, standard patrulje',
  },
];
